--
-- PostgreSQL database dump
--

\restrict aF2mM7Nntu6lo90qqDTwGPS5iGeh7ANcYSM0eFH0PuLCwrPYHrUJCmRF00h7lGn

-- Dumped from database version 17.9
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: agent_config_revisions; Type: TABLE DATA; Schema: public; Owner: paperclip
--

INSERT INTO public.agent_config_revisions VALUES ('93e40bce-09cc-430d-af1a-3b339b546ef0', 'd614ecc3-b46c-47cc-af90-7d2b33e0a47e', 'f17e51ca-4c4c-47bb-8c4b-84516ab5505c', '635f3a34-c54a-4b59-ab25-e73fc30b6cf3', NULL, 'instructions_path_patch', NULL, '["adapterConfig"]', '{"name": "Engineering Manager", "role": "pm", "title": "Engineering Project Manager", "metadata": null, "reportsTo": "635f3a34-c54a-4b59-ab25-e73fc30b6cf3", "adapterType": "claude_local", "capabilities": "Receives engineering tasks, project requests, and technical problems. Breaks down work into actionable subtasks. Delegates to Frontend UI Engineer and Backend Engineer. Manages sprint priorities and unblocks the engineering team. Reviews technical proposals and ensures quality delivery.", "adapterConfig": {"graceSec": 15, "timeoutSec": 0, "maxTurnsPerRun": 200, "instructionsBundleMode": "managed", "dangerouslySkipPermissions": true}, "runtimeConfig": {"heartbeat": {"enabled": true, "intervalSec": 1800, "wakeOnDemand": true, "maxConcurrentRuns": 1}}, "budgetMonthlyCents": 0}', '{"name": "Engineering Manager", "role": "pm", "title": "Engineering Project Manager", "metadata": null, "reportsTo": "635f3a34-c54a-4b59-ab25-e73fc30b6cf3", "adapterType": "claude_local", "capabilities": "Receives engineering tasks, project requests, and technical problems. Breaks down work into actionable subtasks. Delegates to Frontend UI Engineer and Backend Engineer. Manages sprint priorities and unblocks the engineering team. Reviews technical proposals and ensures quality delivery.", "adapterConfig": {"graceSec": 15, "timeoutSec": 0, "maxTurnsPerRun": 200, "instructionsFilePath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/f17e51ca-4c4c-47bb-8c4b-84516ab5505c/instructions/AGENTS.md", "instructionsRootPath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/f17e51ca-4c4c-47bb-8c4b-84516ab5505c/instructions", "instructionsEntryFile": "AGENTS.md", "instructionsBundleMode": "managed", "dangerouslySkipPermissions": true}, "runtimeConfig": {"heartbeat": {"enabled": true, "intervalSec": 1800, "wakeOnDemand": true, "maxConcurrentRuns": 1}}, "budgetMonthlyCents": 0}', '2026-03-30 13:15:48.612828+00');
INSERT INTO public.agent_config_revisions VALUES ('6f61f79a-7f9d-4803-8e4c-d449361d5d16', 'd614ecc3-b46c-47cc-af90-7d2b33e0a47e', '3071507e-da74-46bd-b521-cf16eb00f9b4', 'f17e51ca-4c4c-47bb-8c4b-84516ab5505c', NULL, 'instructions_path_patch', NULL, '["adapterConfig"]', '{"name": "Frontend Engineer", "role": "engineer", "title": "Frontend UI Engineer", "metadata": null, "reportsTo": "f17e51ca-4c4c-47bb-8c4b-84516ab5505c", "adapterType": "claude_local", "capabilities": "Builds and maintains frontend user interfaces using JavaScript, TypeScript, CSS, and modern frameworks (React, Vue, Next.js, Tailwind). Follows test-driven development (TDD) patterns — writes tests first, then implements. Always verifies changes pass tests and linting before committing. Communicates with Engineering Manager for task clarification and progress updates. Coordinates with Backend Engineers before implementing features that require API integration or backend cooperation. Produces accessible, responsive, and performant UI components.", "adapterConfig": {"graceSec": 15, "timeoutSec": 0, "maxTurnsPerRun": 200, "instructionsBundleMode": "managed", "dangerouslySkipPermissions": true}, "runtimeConfig": {"heartbeat": {"enabled": true, "intervalSec": 1800, "wakeOnDemand": true, "maxConcurrentRuns": 1}}, "budgetMonthlyCents": 0}', '{"name": "Frontend Engineer", "role": "engineer", "title": "Frontend UI Engineer", "metadata": null, "reportsTo": "f17e51ca-4c4c-47bb-8c4b-84516ab5505c", "adapterType": "claude_local", "capabilities": "Builds and maintains frontend user interfaces using JavaScript, TypeScript, CSS, and modern frameworks (React, Vue, Next.js, Tailwind). Follows test-driven development (TDD) patterns — writes tests first, then implements. Always verifies changes pass tests and linting before committing. Communicates with Engineering Manager for task clarification and progress updates. Coordinates with Backend Engineers before implementing features that require API integration or backend cooperation. Produces accessible, responsive, and performant UI components.", "adapterConfig": {"graceSec": 15, "timeoutSec": 0, "maxTurnsPerRun": 200, "instructionsFilePath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/3071507e-da74-46bd-b521-cf16eb00f9b4/instructions/AGENTS.md", "instructionsRootPath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/3071507e-da74-46bd-b521-cf16eb00f9b4/instructions", "instructionsEntryFile": "AGENTS.md", "instructionsBundleMode": "managed", "dangerouslySkipPermissions": true}, "runtimeConfig": {"heartbeat": {"enabled": true, "intervalSec": 1800, "wakeOnDemand": true, "maxConcurrentRuns": 1}}, "budgetMonthlyCents": 0}', '2026-03-30 13:20:14.124457+00');
INSERT INTO public.agent_config_revisions VALUES ('ada927c0-d0fe-4b9e-8799-5acaa532b20a', 'd614ecc3-b46c-47cc-af90-7d2b33e0a47e', 'beb6459f-8b56-4270-a1e8-6043dd575548', 'f17e51ca-4c4c-47bb-8c4b-84516ab5505c', NULL, 'instructions_path_patch', NULL, '["adapterConfig"]', '{"name": "Backend Engineer", "role": "engineer", "title": "Backend Engineer", "metadata": null, "reportsTo": "f17e51ca-4c4c-47bb-8c4b-84516ab5505c", "adapterType": "claude_local", "capabilities": "Builds and maintains server-side applications, APIs, database schemas, business logic, integrations, infrastructure, and backend performance. Uses Node.js, Python, SQL, and modern backend frameworks. Follows test-driven development (TDD) patterns — writes tests first, then implements. Always verifies changes pass tests and linting before committing. Communicates with Engineering Manager for task clarification and progress updates. Coordinates with Frontend Engineers on API contracts and integration points. Produces reliable, secure, and performant backend services.", "adapterConfig": {"graceSec": 15, "timeoutSec": 0, "maxTurnsPerRun": 200, "instructionsBundleMode": "managed", "dangerouslySkipPermissions": true}, "runtimeConfig": {"heartbeat": {"enabled": true, "intervalSec": 1800, "wakeOnDemand": true, "maxConcurrentRuns": 1}}, "budgetMonthlyCents": 0}', '{"name": "Backend Engineer", "role": "engineer", "title": "Backend Engineer", "metadata": null, "reportsTo": "f17e51ca-4c4c-47bb-8c4b-84516ab5505c", "adapterType": "claude_local", "capabilities": "Builds and maintains server-side applications, APIs, database schemas, business logic, integrations, infrastructure, and backend performance. Uses Node.js, Python, SQL, and modern backend frameworks. Follows test-driven development (TDD) patterns — writes tests first, then implements. Always verifies changes pass tests and linting before committing. Communicates with Engineering Manager for task clarification and progress updates. Coordinates with Frontend Engineers on API contracts and integration points. Produces reliable, secure, and performant backend services.", "adapterConfig": {"graceSec": 15, "timeoutSec": 0, "maxTurnsPerRun": 200, "instructionsFilePath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/beb6459f-8b56-4270-a1e8-6043dd575548/instructions/AGENTS.md", "instructionsRootPath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/beb6459f-8b56-4270-a1e8-6043dd575548/instructions", "instructionsEntryFile": "AGENTS.md", "instructionsBundleMode": "managed", "dangerouslySkipPermissions": true}, "runtimeConfig": {"heartbeat": {"enabled": true, "intervalSec": 1800, "wakeOnDemand": true, "maxConcurrentRuns": 1}}, "budgetMonthlyCents": 0}', '2026-03-30 14:36:22.739062+00');
INSERT INTO public.agent_config_revisions VALUES ('914042ae-8dcf-4723-807d-5d02fce2a0b7', 'd614ecc3-b46c-47cc-af90-7d2b33e0a47e', '1a865d2d-3b6d-4ac6-b3c4-4ccfbb9c8a30', '635f3a34-c54a-4b59-ab25-e73fc30b6cf3', NULL, 'instructions_path_patch', NULL, '["adapterConfig"]', '{"name": "General Counsel", "role": "general", "title": "General Counsel & Chief Legal Officer", "metadata": null, "reportsTo": "635f3a34-c54a-4b59-ab25-e73fc30b6cf3", "adapterType": "claude_local", "capabilities": "Handles all legal procedures, proceedings, and matters. Composes, edits, evaluates, and reviews legal documents including contracts, agreements, policies, and compliance frameworks. Monitors regulatory compliance and enforces legal standards across the organization. Protects intellectual property and proprietary information. Evaluates and improves legal structure and corporate governance. Has authority to halt any activity deemed illegal or non-compliant until the CEO reviews and provides clearance. Maintains strict confidentiality — does not disclose work product or legal matters to other agents. Reports exclusively to the CEO.", "adapterConfig": {"graceSec": 15, "timeoutSec": 0, "maxTurnsPerRun": 200, "instructionsBundleMode": "managed", "dangerouslySkipPermissions": true}, "runtimeConfig": {"heartbeat": {"enabled": true, "intervalSec": 1800, "wakeOnDemand": true, "maxConcurrentRuns": 1}}, "budgetMonthlyCents": 0}', '{"name": "General Counsel", "role": "general", "title": "General Counsel & Chief Legal Officer", "metadata": null, "reportsTo": "635f3a34-c54a-4b59-ab25-e73fc30b6cf3", "adapterType": "claude_local", "capabilities": "Handles all legal procedures, proceedings, and matters. Composes, edits, evaluates, and reviews legal documents including contracts, agreements, policies, and compliance frameworks. Monitors regulatory compliance and enforces legal standards across the organization. Protects intellectual property and proprietary information. Evaluates and improves legal structure and corporate governance. Has authority to halt any activity deemed illegal or non-compliant until the CEO reviews and provides clearance. Maintains strict confidentiality — does not disclose work product or legal matters to other agents. Reports exclusively to the CEO.", "adapterConfig": {"graceSec": 15, "timeoutSec": 0, "maxTurnsPerRun": 200, "instructionsFilePath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/1a865d2d-3b6d-4ac6-b3c4-4ccfbb9c8a30/instructions/AGENTS.md", "instructionsRootPath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/1a865d2d-3b6d-4ac6-b3c4-4ccfbb9c8a30/instructions", "instructionsEntryFile": "AGENTS.md", "instructionsBundleMode": "managed", "dangerouslySkipPermissions": true}, "runtimeConfig": {"heartbeat": {"enabled": true, "intervalSec": 1800, "wakeOnDemand": true, "maxConcurrentRuns": 1}}, "budgetMonthlyCents": 0}', '2026-03-31 08:39:46.893057+00');
INSERT INTO public.agent_config_revisions VALUES ('a6c7b672-d640-43b8-a09f-4443d343f53f', 'd614ecc3-b46c-47cc-af90-7d2b33e0a47e', '25b0ef20-c35a-4db2-a8cd-841d46dfedcd', '635f3a34-c54a-4b59-ab25-e73fc30b6cf3', NULL, 'instructions_path_patch', NULL, '["adapterConfig"]', '{"name": "Paralegal", "role": "general", "title": "Paralegal & Legal Operations Specialist", "metadata": null, "reportsTo": "1a865d2d-3b6d-4ac6-b3c4-4ccfbb9c8a30", "adapterType": "claude_local", "capabilities": "Performs all legal legwork including due diligence, legal research, document processing, compliance data gathering, and cross-agent coordination. Works with the Research Specialist for data sourcing and the Executive Assistant for CEO communications. Prepares all work product for General Counsel review. Does not issue legal opinions or make compliance determinations.", "adapterConfig": {"graceSec": 15, "timeoutSec": 0, "maxTurnsPerRun": 200, "instructionsBundleMode": "managed", "dangerouslySkipPermissions": true}, "runtimeConfig": {"heartbeat": {"enabled": true, "intervalSec": 1800, "wakeOnDemand": true, "maxConcurrentRuns": 1}}, "budgetMonthlyCents": 0}', '{"name": "Paralegal", "role": "general", "title": "Paralegal & Legal Operations Specialist", "metadata": null, "reportsTo": "1a865d2d-3b6d-4ac6-b3c4-4ccfbb9c8a30", "adapterType": "claude_local", "capabilities": "Performs all legal legwork including due diligence, legal research, document processing, compliance data gathering, and cross-agent coordination. Works with the Research Specialist for data sourcing and the Executive Assistant for CEO communications. Prepares all work product for General Counsel review. Does not issue legal opinions or make compliance determinations.", "adapterConfig": {"graceSec": 15, "timeoutSec": 0, "maxTurnsPerRun": 200, "instructionsFilePath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/25b0ef20-c35a-4db2-a8cd-841d46dfedcd/instructions/AGENTS.md", "instructionsRootPath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/25b0ef20-c35a-4db2-a8cd-841d46dfedcd/instructions", "instructionsEntryFile": "AGENTS.md", "instructionsBundleMode": "managed", "dangerouslySkipPermissions": true}, "runtimeConfig": {"heartbeat": {"enabled": true, "intervalSec": 1800, "wakeOnDemand": true, "maxConcurrentRuns": 1}}, "budgetMonthlyCents": 0}', '2026-03-31 09:19:02.555291+00');
INSERT INTO public.agent_config_revisions VALUES ('1b9522c8-9a5a-497c-b545-f9b9bad8aa0c', 'd614ecc3-b46c-47cc-af90-7d2b33e0a47e', '029b2109-796f-4970-a727-88424580c1d9', '635f3a34-c54a-4b59-ab25-e73fc30b6cf3', NULL, 'patch', NULL, '["name"]', '{"name": "Executive Assistant", "role": "general", "title": "Executive Assistant to the CEO", "metadata": null, "reportsTo": "635f3a34-c54a-4b59-ab25-e73fc30b6cf3", "adapterType": "claude_local", "capabilities": "Tracks and follows up on delegated work across all teams. Prepares status summaries and progress reports. Manages task prioritization and scheduling. Coordinates cross-functional communication. Executes routine operational tasks on behalf of the CEO. Surfaces blockers and escalates proactively. Maintains organizational context and institutional memory.", "adapterConfig": {"graceSec": 15, "timeoutSec": 0, "maxTurnsPerRun": 200, "instructionsFilePath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/029b2109-796f-4970-a727-88424580c1d9/instructions/AGENTS.md", "instructionsRootPath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/029b2109-796f-4970-a727-88424580c1d9/instructions", "instructionsEntryFile": "AGENTS.md", "instructionsBundleMode": "managed", "dangerouslySkipPermissions": true}, "runtimeConfig": {"heartbeat": {"enabled": true, "intervalSec": 1800, "wakeOnDemand": true, "maxConcurrentRuns": 1}}, "budgetMonthlyCents": 0}', '{"name": "Marie", "role": "general", "title": "Executive Assistant to the CEO", "metadata": null, "reportsTo": "635f3a34-c54a-4b59-ab25-e73fc30b6cf3", "adapterType": "claude_local", "capabilities": "Tracks and follows up on delegated work across all teams. Prepares status summaries and progress reports. Manages task prioritization and scheduling. Coordinates cross-functional communication. Executes routine operational tasks on behalf of the CEO. Surfaces blockers and escalates proactively. Maintains organizational context and institutional memory.", "adapterConfig": {"graceSec": 15, "timeoutSec": 0, "maxTurnsPerRun": 200, "instructionsFilePath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/029b2109-796f-4970-a727-88424580c1d9/instructions/AGENTS.md", "instructionsRootPath": "/paperclip/instances/default/companies/d614ecc3-b46c-47cc-af90-7d2b33e0a47e/agents/029b2109-796f-4970-a727-88424580c1d9/instructions", "instructionsEntryFile": "AGENTS.md", "instructionsBundleMode": "managed", "dangerouslySkipPermissions": true}, "runtimeConfig": {"heartbeat": {"enabled": true, "intervalSec": 1800, "wakeOnDemand": true, "maxConcurrentRuns": 1}}, "budgetMonthlyCents": 0}', '2026-03-31 09:45:11.943548+00');


--
-- PostgreSQL database dump complete
--

\unrestrict aF2mM7Nntu6lo90qqDTwGPS5iGeh7ANcYSM0eFH0PuLCwrPYHrUJCmRF00h7lGn

